branch-defaults:
  default:
    environment: Portal
  master:
    environment: Portal
environment-defaults:
  Portal:
    branch: null
    repository: null
global:
  application_name: Connectedin
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
